### ISSUE TITLE
Not compatible with MyParcel extension

### ISSUE THREAD

**Issue by gerben86** [wezzco/postcode-m2#4]
I'm using the MyParcel extension (https://github.com/myparcelnl/magento), but when I use the Postcode-m2 extension and MyParcel there are no shipping options shown anymore.

But I see the request to the MyParcel-api is done and a reply was given.
Could you check how I could solve this issue?
Because I like to have both in my webshop, postcode validation AND shipping options.

**Comment by nealz** [comment]
Unfortunately the extension does not support MyParcel at this moment. If we have more request on supporting MyParcel then we could support this in future releases.
